[[main]]
name = "ğŸ  Home"
url = "/"
weight = 1

[[main]]
name = "ğŸ“ Posts"
url = "/posts/"
weight = 2

[[main]]
name = "ğŸ·ï¸ Categories"
url = "/categories/"
weight = 3

[[main]]
name = "ğŸ” Search"
url = "/search/"
weight = 6

[[main]]
name = "About"
url = "/about"
weight = 17
