[[main]]
name = "Home"
url = "/"
icon = "home"
weight = 1

[[main]]
name = "Posts"
url = "/posts/"
icon = "posts"
weight = 2

[[main]]
name = "Categories"
url = "/categories/"
icon = "categories"
weight = 3

[[main]]
name = "Search"
url = "/search/"
icon = "search"
weight = 6

[[main]]
name = "About"
url = "/about"
icon = "about"
weight = 17
