[[main]]
name = "Home"
url = "/"
icon = "home"
weight = 1

[[main]]
name = "Posts"
weight = 1
[main.params]
icon = "home"

[[main]]
name = "ğŸ“ Posts"
url = "/posts/"
weight = 2
[main.params]
icon = "edit"

[[main]]
name = "ğŸ·ï¸ Categories"
url = "/categories/"
weight = 3
[main.params]
icon = "category"

[[main]]
name = "ğŸ“¦ Products"
url = "/categories/products/"
weight = 4
[main.params]
icon = "package"

[[main]]
name = "ğŸ” Search"
url = "/search/"
weight = 6
[main.params]
icon = "search"

[[main]]
name = "About"
url = "/about"
weight = 17
[main.params]
icon = "info"
